# example netlify.toml
[build]
command = "nuxt build"
functions = "netlify/functions"
publish = ".nuxt"

# publish = "dist"
## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.
[[redirects]]
from = "/*"
to = "/.netlify/functions/render"
status = 200

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
command = "yarn dev" # Command to start your dev server
port = 3001 # Port that the dev server will be listening on
publish = ".nuxt" # Folder with the static content for _redirect file
## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
